# squirrel_data.py
SQUIRREL_FACTS = [
    "A squirrel's front teeth never stop growing—they can grow 6 inches a year.",
    "Squirrels can find food buried beneath a foot of snow.",
    "The word 'squirrel' comes from Greek words meaning 'shadow tail'.",
    "They run in a zigzag pattern to escape predators.",
    "A squirrel’s brain is roughly the size of a walnut.",
    "Squirrels can fall from 100 feet and land without getting hurt.",
    "They 'fake' burying nuts to trick thieves.",
    "Some squirrels, like the Flying Squirrel, actually glide using a membrane.",
    "Squirrels plant thousands of trees every year by forgetting their nuts.",
    "A group of squirrels is called a 'scurry' or a 'dray'.",
    "Squirrels can jump up to 20 feet in a single leap.",
    "Their hind legs are double-jointed, allowing them to run down trees head-first.",
    "Squirrels can eat their own body weight in seeds and nuts every week.",
    "A male squirrel can smell a female in heat from a mile away.",
    "Squirrels have 4 toes on front feet and 5 toes on back feet.",
    "There are over 285 species of squirrels globally.",
    "Arctic ground squirrels can survive body temperatures below freezing.",
    "Squirrels' eyes are positioned to see behind them.",
    "Iran once claimed 14 squirrels found near its borders were 'spies'.",
    "Squirrels were trained for the 2005 movie 'Charlie and the Chocolate Factory'.",
    "A squirrel's nest is called a 'drey'.",
    "Squirrels are born blind and hairless.",
    "The rarest squirrel is the albino squirrel.",
    "Squirrels listen to birdsong to detect if predators are nearby.",
    "Squirrels use their tails as rudders when swimming.",
    "Miss Baker was the first squirrel to travel to space in 1959.",
    "Some squirrels are omnivores and will eat bird eggs.",
    "Squirrels can run up to 20 miles per hour.",
    "Ground squirrels like marmots are part of the squirrel family.",
    "An adult squirrel can bury 25 nuts in just one hour.",
    "Gray squirrels use their tails as umbrellas during rain.",
    "Squirrels must drink water at least twice a day.",
    "The Indian Giant Squirrel can be up to 3 feet long.",
    "Squirrels use 'spatial chunking' to organize their nut caches.",
    "Tree squirrels can rotate their ankles 180 degrees.",
    "The Gray Squirrel weighs only half an ounce at birth.",
    "Flying squirrels have cartilage spurs at their wrists to steer.",
    "Red squirrels are smaller and more aggressive than gray squirrels.",
    "Squirrels communicate using high-pitched chirps and tail flagging.",
    "A baby squirrel is officially called a 'kit'.",
    "Squirrels have excellent peripheral vision.",
    "A squirrel's tail acts as a built-in blanket in winter.",
    "Southern fox squirrels are twice the size of gray squirrels.",
    "Squirrels scent-mark territory by rubbing their cheeks on branches.",
    "Ground squirrels hibernate, but tree squirrels do not.",
    "Squirrels will steal nuts from bird feeders frequently.",
    "The average lifespan in the wild is about 6 years.",
    "Squirrels help spread truffle spores through digestion.",
    "In the 1800s, squirrels were introduced to US parks for beauty.",
    "Squirrels can swim by using their legs like paddles.",
    "Pheromones in squirrel saliva help them communicate status.",
    "A squirrel's tail can serve as a shield during a fight.",
    "Squirrels lose up to 25% of body weight during winter.",
    "Some squirrels 'alarm bark' for 20 minutes at cats.",
    "The Southern Flying Squirrel is strictly nocturnal.",
    "Squirrels use landmarks like specific logs as living GPS.",
    "Chipmunks are actually a type of ground squirrel.",
    "Black squirrels are a melanistic subgroup of Gray squirrels.",
    "Squirrels have whiskers on their legs to help navigate.",
    "A squirrel's tail can be used as a cooling fan in summer.",
    "Gray squirrels can jump 5 feet vertically.",
    "Squirrels often build 'backup' nests for emergencies.",
    "Japanese Giant Flying Squirrels can glide for 500 feet.",
    "Squirrels prefer sunflower seeds over most other foods.",
    "A squirrel's digestive tract is about 7 feet long.",
    "In some cultures, squirrels are symbols of thriftiness.",
    "Squirrels survive falls due to low terminal velocity.",
    "Squirrels are known to raid gardens for tomatoes.",
    "The African Pygmy Squirrel is only 3 inches long.",
    "Squirrels have been known to adopt orphaned kits.",
    "The zigzag run forces predators to adjust momentum.",
    "Ground squirrels live in burrow systems called 'towns'.",
    "Squirrels find buried nuts using a strong sense of smell.",
    "The most common US squirrel is the Eastern Gray Squirrel.",
    "Squirrels are key prey for hawks, owls, and snakes.",
    "Squirrels eat fungi that would be toxic to humans.",
    "The name 'drey' comes from an Old English word for 'nest'.",
    "Squirrels can be trained to eat out of a person's hand.",
    "The Indian Palm Squirrel has three stripes on its back.",
    "The gestation period for a gray squirrel is 44 days.",
    "Squirrels forage for food 2 hours after sunrise.",
    "Flying squirrels can turn at right angles in mid-air.",
    "Squirrels remember thousands of cache locations for months.",
    "Squirrels' front paws are as dexterous as human hands.",
    "The largest squirrel in the world is the Alpine Marmot.",
    "Squirrels live in altitudes up to 12,000 feet.",
    "A 'tail flick' is a sign of squirrel frustration.",
    "Squirrels share nests in winter to conserve heat.",
    "The Sciuridae family has existed for 30 million years.",
    "Squirrels can't digest cellulose well.",
    "Squirrels avoid eating most leaves and bark.",
    "Squirrels have fur colors ranging from white to pitch black.",
    "The 'scurry' is characterized by sudden stops and starts.",
    "Squirrels have a sweet tooth for maple sap.",
    "January 21st is Squirrel Appreciation Day.",
    "Gray squirrels were introduced to Britain in the 1870s.",
    "Red squirrels are the only native squirrel in the UK.",
    "Squirrels can smell a buried acorn through a foot of dirt.",
    "A squirrel's tail helps it stay balanced on telephone wires.",
    "Eastern Gray Squirrels can hoard up to 10,000 nuts a year.",
    "Squirrels use their tail to signal 'all clear' to others.",
    "Ground squirrels can have complex social hierarchies.",
    "Flying squirrels glide by stretching their legs out wide.",
    "Squirrels can be right-handed or left-handed when holding nuts.",
    "They use their sharp claws to grip bark at high speeds.",
    "Squirrels often twitch their noses to detect predators.",
    "A squirrel's tail is roughly the same length as its body.",
    "They can recognize individual humans who feed them.",
    "Squirrels will eat bark if no other food is available.",
    "Fox squirrels can weigh up to 2 pounds.",
    "The Malabar Giant Squirrel is known as the 'rainbow squirrel'.",
    "Squirrels can jump horizontally 10 times their body length.",
    "Some squirrels live in hollowed-out cacti in the desert.",
    "Ground squirrels use ultrasound to communicate secretly.",
    "Squirrels can identify the best nuts by weighing them in their paws.",
    "A squirrel's heart beats 100 times per minute during sleep.",
    "Squirrels have sweat glands only on their feet.",
    "They can hang by their back legs to reach bird feeders.",
    "The word 'Sciurus' means 'tail-waver' in Latin.",
    "Squirrels are found in every continent except Australia.",
    "They have a blind spot directly in front of their nose.",
    "Squirrels will chew on bones for calcium.",
    "They can climb down a tree headfirst by rotating their ankles.",
    "A squirrel's drey is usually 30 feet or higher in a tree.",
    "They use soft moss and fur to line their nests.",
    "Squirrels can live up to 20 years in captivity.",
    "Gray squirrels have a white underbelly to blend with the sky.",
    "Squirrels are known to 'scold' dogs from high branches.",
    "They can eat pinecones by stripping the scales off.",
    "A squirrel's jump is powered by its strong back legs.",
    "They can change direction in mid-air using their tail.",
    "Squirrels are most active in the early morning and late afternoon.",
    "They can remember the most direct path to a food source.",
    "Squirrels will sometimes share food with their siblings.",
    "The flying squirrel's membrane is called a patagium.",
    "Squirrels can shiver to produce heat in the winter.",
    "They have a highly developed sense of touch in their paws.",
    "A squirrel's tail can act as a distraction for predators.",
    "Squirrels can survive on a diet of mostly seeds.",
    "They are known to be very curious animals.",
    "Squirrels can solve complex puzzles to get to food.",
    "They use their tail to shade themselves from the sun.",
    "Squirrels can hear high-frequency sounds humans can't.",
    "They can distinguish between different types of trees.",
    "A squirrel's brain is highly focused on memory.",
    "They can identify a 'bad' nut without opening it.",
    "Squirrels will sometimes 'play' with each other.",
    "They can climb up a brick wall with ease.",
    "Squirrels have very strong jaw muscles for their size.",
    "They can eat up to 20 acorns in one sitting.",
    "A squirrel's fur is very dense to provide insulation.",
    "They can jump from one tree to another with precision.",
    "Squirrels use their tail to keep their balance on thin branches.",
    "They can swim across small rivers if necessary.",
    "Squirrels have a very fast metabolism.",
    "They can store food in their cheek pouches temporarily.",
    "A squirrel's whiskers help it judge the width of openings.",
    "They can see colors, but not as well as humans.",
    "Squirrels are very protective of their young.",
    "They can learn to navigate an obstacle course quickly.",
    "A squirrel's tail is very flexible.",
    "They can jump down from great heights safely.",
    "Squirrels are known for their 'chattering' vocalizations.",
    "They can find their way home from long distances.",
    "A squirrel's nest is very sturdy and weather-resistant.",
    "They can eat a variety of fruits and vegetables.",
    "Squirrels are often seen chasing each other in trees.",
    "They can use their tail to signal danger to other squirrels.",
    "A squirrel's claws are very sharp and curved.",
    "They can grip onto smooth surfaces with their claws.",
    "Squirrels are very agile and can turn quickly.",
    "They can jump over large gaps between buildings.",
    "A squirrel's tail is covered in long, bushy fur.",
    "They can use their tail as a rudder when gliding.",
    "Squirrels are known to be very energetic animals.",
    "They can find food in even the smallest of crevices.",
    "A squirrel's eyes are large and dark.",
    "They can see well in low-light conditions.",
    "Squirrels are very observant of their surroundings.",
    "They can learn to associate certain sounds with food.",
    "A squirrel's tail can be used to signal its mood.",
    "They can jump from a stationary position with great force.",
    "Squirrels are known to be very resourceful.",
    "They can use their paws to manipulate small objects.",
    "A squirrel's fur can change color slightly with the seasons.",
    "They can survive in a variety of different climates.",
    "Squirrels are very good at finding hidden food.",
    "They can use their tail to keep warm in cold weather.",
    "A squirrel's nest is often located in the fork of a tree.",
    "They can eat a wide range of nuts and seeds.",
    "Squirrels are known for their quick movements.",
    "They can climb up and down trees with great speed.",
    "A squirrel's tail is an essential part of its body.",
    "They can use their tail to communicate with other squirrels.",
    "Squirrels are very intelligent and can solve problems.",
    "They can remember the location of their nests.",
    "A squirrel's fur is often mottled to provide camouflage.",
    "They can jump across wide spaces with ease.",
    "Squirrels are known for their ability to adapt to new environments.",
    "They can find food in a variety of different places.",
    "A squirrel's eyes are located on the sides of its head.",
    "They can see a wide field of view without moving their head.",
    "Squirrels are very alert and can detect predators quickly.",
    "They can use their tail to signal a variety of different things.",
    "A squirrel's claws are essential for climbing.",
    "They can grip onto bark with great strength.",
    "Squirrels are very active during the daylight hours.",
    "They can find food even in the middle of winter.",
    "A squirrel's tail is a very important tool for survival.",
    "They can use their tail to help them stay balanced while running.",
    "Squirrels are very good at jumping and climbing.",
    "They can navigate through dense foliage with ease.",
    "A squirrel's fur is very soft and thick.",
    "They can use their tail to help them stay warm while sleeping.",
    "Squirrels are known for their curious and playful nature.",
    "They can find food in even the most unlikely of places.",
    "A squirrel's nest is a safe place for it to rest.",
    "They can eat a variety of different kinds of food.",
    "Squirrels are very quick and agile animals.",
    "They can climb trees with great ease and speed.",
    "A squirrel's tail is a very distinctive feature.",
    "They can use their tail to communicate with their peers.",
    "Squirrels are very smart and can learn new things.",
    "They can remember the location of their food caches for a long time.",
    "A squirrel's fur provides it with protection from the elements.",
    "They can jump long distances with great accuracy.",
    "Squirrels are known for their ability to find food in the wild.",
    "They can adapt to living in many different kinds of habitats.",
    "A squirrel's eyes are very sensitive to movement.",
    "They can see predators from a long distance away.",
    "Squirrels are very good at hiding from danger.",
    "They can use their tail to signal to other squirrels about food.",
    "A squirrel's claws are very strong and can grip onto many surfaces.",
    "They can climb up and down trees with great confidence.",
    "Squirrels are very active and spend much of their time foraging.",
    "They can find food in many different ways.",
    "A squirrel's tail is a very versatile appendage.",
    "They can use their tail to help them stay balanced while jumping.",
    "Squirrels are very skilled at navigating through their environment.",
    "They can find their way through complex mazes of branches.",
    "A squirrel's fur is an important part of its survival strategy.",
    "They can use their tail to help them stay warm in the winter.",
    "Squirrels are known for their cleverness and resourcefulness.",
    "They can find food in many different kinds of environments.",
    "A squirrel's nest is a place of safety and security.",
    "They can eat many different kinds of nuts, seeds, and fruits.",
    "Squirrels are very fast and can escape from many predators.",
    "They can climb trees with great agility and speed.",
    "A squirrel's tail is a very important part of its anatomy.",
    "They can use their tail to communicate with other members of their scurry.",
    "Squirrels are very intelligent and can solve many different kinds of problems.",
    "They can remember the location of many different food caches.",
    "A squirrel's fur is very thick and provides excellent insulation.",
    "They can jump across large gaps with great precision.",
    "Squirrels are known for their ability to find food even in difficult conditions.",
    "They can adapt to living in many different kinds of climates and habitats.",
    "A squirrel's eyes provide it with a wide field of vision.",
    "They can see movement from a long distance away.",
    "Squirrels are very alert and are always on the lookout for danger.",
    "They can use their tail to signal to other squirrels about many different things.",
    "A squirrel's claws are very sharp and are used for climbing and gripping.",
    "They can climb trees with great speed and agility.",
    "Squirrels are very active during the day and spend much of their time looking for food.",
    "They can find food in many different and creative ways.",
    "A squirrel's tail is a very important and versatile tool.",
    "They can use their tail to help them stay balanced in many different situations.",
    "Squirrels are very skilled at navigating through their complex environment.",
    "They can find their way through even the densest of forests.",
    "A squirrel's fur is an essential part of its survival in the wild.",
    "They can use their tail to stay warm and dry in the winter.",
    "Squirrels are known for their intelligence and their ability to learn.",
    "They can find food in many different and challenging environments.",
    "A squirrel's nest is a secure and comfortable place to live.",
    "They can eat a wide variety of different nuts, seeds, and berries.",
    "Squirrels are very quick and can evade many different predators.",
    "They can climb trees with great speed and dexterity.",
    "A squirrel's tail is a very distinctive and useful part of its body.",
    "They can use their tail to communicate with other squirrels in many ways.",
    "Squirrels are very intelligent and are capable of solving complex problems.",
    "They can remember the location of their food caches for many months.",
    "A squirrel's fur provides it with excellent camouflage in its natural habitat.",
    "They can jump long distances with great accuracy and confidence.",
    "Squirrels are known for their ability to find food even in the harshest of conditions.",
    "They can adapt to living in a wide range of different environments.",
    "A squirrel's eyes are very good at detecting movement from a distance.",
    "They can see predators and other threats quickly and easily.",
    "Squirrels are very alert and are always aware of what is happening around them.",
    "They can use their tail to signal to other squirrels about potential danger.",
    "A squirrel's claws are very strong and are used for a variety of tasks.",
    "They can climb trees with great speed, agility, and precision.",
    "Squirrels are very active animals and spend most of their time foraging for food.",
    "They can find food in a wide variety of different and interesting ways.",
    "A squirrel's tail is a very important and useful part of its survival kit.",
    "They can use their tail to maintain their balance in many different settings.",
    "Squirrels are very skilled at navigating through the branches of trees.",
    "They can find their way through even the most complex of environments.",
    "A squirrel's fur is a key part of its ability to survive in the wild.",
    "They can use their tail to stay warm and protected from the weather.",
    "Squirrels are known for their cleverness, intelligence, and curiosity.",
    "They can find food in many different and often surprising places.",
    "A squirrel's nest is a safe and cozy place for it to sleep and rest.",
    "They can eat many different kinds of nuts, seeds, fruits, and insects.",
    "Squirrels are very fast and can easily escape from many of their predators.",
    "They can climb trees with great speed, skill, and confidence.",
    "A squirrel's tail is a very important and multi-functional part of its body.",
    "They can use their tail to communicate with other squirrels in a variety of ways.",
    "Squirrels are very intelligent animals and are capable of complex learning.",
    "They can remember the location of many thousands of different food caches.",
    "A squirrel's fur is very thick and provides it with great protection from the cold.",
    "They can jump across wide gaps with great skill and accuracy.",
    "Squirrels are known for their ability to find food in many different types of terrain.",
    "They can adapt to living in many different kinds of environments and climates.",
    "A squirrel's eyes provide it with an excellent field of vision for spotting threats.",
    "They can see movement from a great distance and respond quickly.",
    "Squirrels are very observant and are always watching their surroundings.",
    "They can use their tail to signal to other squirrels about food and danger.",
    "A squirrel's claws are very sharp and are essential for its life in the trees.",
    "They can climb up and down trees with great speed and dexterity.",
    "Squirrels are very active during the day and spend much of their time searching for food.",
    "They can find food in many different and often very clever ways.",
    "A squirrel's tail is an essential tool that it uses for many different purposes.",
    "They can use their tail to help them stay balanced while they are on the move.",
    "Squirrels are very skilled at navigating through their aerial environment.",
    "They can find their way through even the most difficult and dense foliage.",
    "A squirrel's fur is an important part of its overall survival strategy in the wild.",
    "They can use their tail to stay warm and comfortable during the cold winter months.",
    "Squirrels are known for their intelligence, curiosity, and resourcefulness.",
    "They can find food in many different and often quite unexpected places.",
    "A squirrel's nest is a safe and secure home where it can raise its young.",
    "They can eat a wide variety of different nuts, seeds, fruits, and even small insects.",
    "Squirrels are very fast and agile, which helps them to stay safe from predators.",
    "They can climb trees with great speed, precision, and confidence.",
    "A squirrel's tail is a very important part of its body that it uses every day.",
    "They can use their tail to communicate with other squirrels in a scurry.",
    "Squirrels are very smart and can solve many different types of challenges.",
    "They can remember the location of their many food caches for a very long time.",
    "A squirrel's fur provides it with warmth and camouflage in its environment.",
    "They can jump long distances with great skill, accuracy, and ease.",
    "Squirrels are known for their ability to find food in even the most difficult conditions.",
    "They can adapt to living in many different types of habitats and climates.",
    "A squirrel's eyes are very sensitive and can detect even the smallest of movements.",
    "They can see predators coming from a long way off and take cover.",
    "Squirrels are very alert and are always paying attention to their surroundings.",
    "They can use their tail to signal to other squirrels about many different things.",
    "A squirrel's claws are very strong and sharp, which is perfect for climbing trees.",
    "They can climb trees with great speed and confidence in their ability.",
    "Squirrels are very active during the day and spend a lot of time looking for food.",
    "They can find food in many different and often very creative ways.",
    "A squirrel's tail is a very important and versatile part of its body.",
    "They can use their tail to maintain their balance in many different environments.",
    "Squirrels are very skilled at navigating through the branches of trees in the forest.",
    "They can find their way through even the most complex and dense environments.",
    "A squirrel's fur is a key part of its survival and helps it stay warm in the winter.",
    "They can use their tail to help them stay warm and dry during the cold weather.",
    "Squirrels are known for their cleverness, curiosity, and their ability to learn.",
    "They can find food in many different and sometimes very surprising places.",
    "A squirrel's nest is a safe and cozy place where it can rest and sleep.",
    "They can eat many different kinds of nuts, seeds, fruits, and even berries.",
    "Squirrels are very fast and can easily escape from many of their predators.",
    "They can climb trees with great speed, skill, and precision every day.",
    "A squirrel's tail is a very important and multi-functional part of its body.",
    "They can use their tail to communicate with other squirrels in many different ways.",
    "Squirrels are very intelligent and are capable of complex learning and memory.",
    "They can remember the location of thousands of different food caches they have made.",
    "A squirrel's fur is very thick and provides it with great protection from the cold weather.",
    "They can jump across wide gaps in the trees with great skill and accuracy.",
    "Squirrels are known for their ability to find food in many different and varied places.",
    "They can adapt to living in many different kinds of environments all over the world.",
    "A squirrel's eyes provide it with an excellent field of vision for spotting any danger.",
    "They can see movement from a great distance and respond very quickly.",
    "Squirrels are very observant and are always watching what is happening around them.",
    "They can use their tail to signal to other squirrels about food sources or danger.",
    "A squirrel's claws are very sharp and are essential for its life climbing in the trees.",
    "They can climb up and down trees with great speed, agility, and dexterity.",
    "Squirrels are very active during the day and spend most of their time searching for food.",
    "They can find food in many different and often very clever and resourceful ways.",
    "A squirrel's tail is an essential tool that it uses for many different tasks every day.",
    "They can use their tail to help them stay balanced while they are running or jumping.",
    "Squirrels are very skilled at navigating through their complex aerial environment.",
    "They can find their way through even the most difficult and dense foliage with ease.",
    "A squirrel's fur is an important part of its overall survival strategy in the wild.",
    "They can use their tail to stay warm and comfortable even in the coldest winter months.",
    "Squirrels are known for their intelligence, curiosity, and their great resourcefulness.",
    "They can find food in many different and often quite unexpected places.",
    "A squirrel's nest is a safe and secure home where it can rest and raise its kits.",
    "They can eat a wide variety of different nuts, seeds, fruits, and occasionally insects.",
    "Squirrels are very fast and agile, which helps them to stay safe from their many predators.",
    "They can climb trees with great speed, precision, and confidence every single day."
]